### ISSUE TITLE
vmwaretools will fail to install on new CentOS7 machines

### ISSUE THREAD

**Issue by anthonysomerset** [craigwatson/puppet-vmwaretools#55]
With vSphere 5.5 and Vmware Tools version: 9.4.10-2068191
puppet will fail to install on new vm's

when you run the same tools install manually the first question is new and defaults to no (exit installer):

    open-vm-tools are available from the OS vendor and VMware recommends using 
    open-vm-tools. See http://kb.vmware.com/kb/2073803 for more information.
    Do you still want to proceed with this legacy installer? [no] 

the behaviour exhibited by Puppet is that it will run the download, extract, install clean routines on every runtime of puppet without actually installing the tools

**Comment by mattiasgeniar** [comment]
A really dirty fix is to pipe 'yes' to the installer;

```
echo 'yes' | ~/vmware-tools-distrib/vmware-install.pl -d
```

**Comment by craigwatson** [comment]
Oof, that is a dirty fix, but it may be the only option!

Would an `override_install` parameter be good, or do you think it's just worth replacing the install command?

**Comment by mattiasgeniar** [comment]
I'm not sure, in my fork of your repo I'm now trying our runs with "echo 'yes' | ...", and so far that's just going fine.

If all the defaults are OK, and there's no prompt, the 'yes' won't do much either. It seems like a safe option, but I'm unsure on what edge cases I haven't thought of yet.

**Comment by craigwatson** [comment]
Thinking about it, `echo 'yes` does much the same as the `-d` switch (i.e. accept all defaults), so I guess there's not much of a difference.

If you can confirm that all seems OK, I'll make the change to master.

**Comment by mattiasgeniar** [comment]
I was wrong indeed, my tests where it seemed to work were actually flawed. Piping yes doesn't work.

So far, there's no fix it seems ...

**Comment by anthonysomerset** [comment]
I can confirm this bug exists on Ubuntu 14.04 LTS as well now

**Comment by anthonysomerset** [comment]
a plain 
`"echo 'yes' | ~/vmware-tools-distrib/vmware-install.pl` without the -d flag appears to work ok

**Comment by craigwatson** [comment]
Thanks @anthonysomerset - @mattiasgeniar can you confirm if this also works for you?

**Comment by mattiasgeniar** [comment]
Confirmed, it works by piping "yes" to the vmware-tools installere, if the -d flag is ommitted.

```
$ echo 'yes' | ./vmware-install.pl
open-vm-tools are available from the OS vendor and VMware recommends using
open-vm-tools. See http://kb.vmware.com/kb/2073803 for more information.
Do you still want to proceed with this legacy installer? [no]
Creating a new VMware Tools installer database using the tar4 format.

Installing VMware Tools.

In which directory do you want to install the binary files?
[/usr/bin]
What is the directory that contains the init directories (rc0.d/ to rc6.d/)?
[/etc/rc.d]
What is the directory that contains the init scripts?
[/etc/rc.d/init.d]
...
```

**Comment by craigwatson** [comment]
Fantastic, thanks @mattiasgeniar and @anthonysomerset.

Can you both pull from master on GitHub and set the `force_install` parameter to `true`?

If it works as expected, I'll release version 1.4.0 of the module to the Forge when time permits :)

**Comment by anthonysomerset** [comment]
this appears to work for ubuntu at least :)

**Comment by anthonysomerset** [comment]
also works on CentOS 7.x

**Comment by craigwatson** [comment]
Thanks for the confirmation, I'll get 1.4.0 out to the Forge tomorrow :)

**Comment by craigwatson** [comment]
Closing this issue as 1.4.0 is now live on the forge - apologies for the delay!

Cheers for your help guys, much appreciated :+1:
