### ISSUE TITLE
Build tools and headers conflict with other puppet modules.

### ISSUE THREAD

**Issue by Aethylred** [craigwatson/puppet-vmwaretools#59]
I use puppetlabs-gcc to install and maintain build tools and headers. https://forge.puppetlabs.com/puppetlabs/gcc

This isn't getting along with puppet-vmwaretools as they're not yeilding to each other over installing common packages.

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[build-essential] is already declared in file /etc/puppet/environments/production/library/vmwaretools/manifests/install/package.pp:51; cannot redeclare at /etc/puppet/environments/production/library/gcc/manifests/init.pp:19 on node git.test.nesi.org.nz
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Making installing the build tools optional would resolve this (making a PR).

**Comment by craigwatson** [comment]
Thanks for the PR, can you test with my slightly revised logic code?

**Comment by Aethylred** [comment]
I'm using it in my current test environment. So it's good.

**Comment by craigwatson** [comment]
Perfect, closing this issue then :)
