### ISSUE TITLE
Failed to apply catalog: Could not find dependency File[/tmp/vmwaretools]

### ISSUE THREAD

**Issue by rantamplan** [craigwatson/puppet-vmwaretools#64]
Hi,

The puppet version deployed is 3.4.3-1puppetlabs1 under a debian 7.8
The module correctly install vmwaretools but after this error:

Error: Failed to apply catalog: Could not find dependency File[/tmp/vmwaretools] for File[/tmp/vmwaretools/VMwareTools-9.0.5-1065307.tar.gz] at /etc/puppet/environments/production/modules/vmwaretools/manifests/install/archive.pp:27

Seem to be related to the creation of the dir, the dir exist.
If i delete the dir i have the same error
If i change download method the same
If i delete vmwaretools, puppet run correctly :(

The error come from my config ? old version of puppet ?

**Comment by craigwatson** [comment]
Hi,

This does look like a bug in the module, does this happen on every Puppet run, and was VMware Tools installed previously (i.e. via open-vm-tools, or VMware OSP)?

Thanks,
Craig

**Comment by jgrumboe** [comment]
It happens on every puppet run and vmware tools where installed with your puppet-vmwaretools version 0.1.2 (really old ;)
We never installed opem-vm-tools or OSP since we don't like this "Third-party tools installed" label in vsphere center VM detail :)

**Comment by rantamplan** [comment]
hi,

don't like the third party too...
using client without openvm-tools installed:
root@debian-client-debian:/var/lib/puppet/lib/facter# puppet agent --test
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /var/lib/puppet/lib/facter/vmwaretools_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/esx_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
Info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
Info: Caching catalog for debian-client-debian.lab.lan
Info: Applying configuration version '1430627125'
Notice: /Stage[main]/Vmwaretools::Config/File[/tmp/vmwaretools]/ensure: created
Notice: /Stage[main]/Vmwaretools::Install::Package/Package[open-vm-dkms]/ensure: ensure changed '2:8.8.0+2012.05.21-724730-1+nmu2' to 'purged'
Notice: /Stage[main]/Vmwaretools::Install::Archive/File[/tmp/vmwaretools/download.sh]/ensure: defined content as '{md5}d0bc968ac908c77d4d584819b12df1ac'
Info: /Stage[main]/Vmwaretools::Install::Archive/File[/tmp/vmwaretools/download.sh]: Scheduling refresh of Exec[download_vmwaretools]
Notice: /Stage[main]/Vmwaretools::Install::Exec/Exec[download_vmwaretools]: Triggered 'refresh' from 1 events
Info: /Stage[main]/Vmwaretools::Install::Exec/Exec[download_vmwaretools]: Scheduling refresh of Exec[uncompress_vmwaretools]
Notice: /Stage[main]/Vmwaretools::Install::Exec/Exec[uncompress_vmwaretools]: Triggered 'refresh' from 1 events
Info: /Stage[main]/Vmwaretools::Install::Exec/Exec[uncompress_vmwaretools]: Scheduling refresh of Exec[install_vmwaretools]
Notice: /Stage[main]/Vmwaretools::Install::Exec/Exec[install_vmwaretools]: Triggered 'refresh' from 1 events
Info: /Stage[main]/Vmwaretools::Install::Exec/Exec[install_vmwaretools]: Scheduling refresh of Exec[clean_vmwaretools]
Notice: /Stage[main]/Vmwaretools::Install::Exec/Exec[clean_vmwaretools]: Triggered 'refresh' from 1 events
Notice: Finished catalog run in 31.93 seconds

a second turn
root@debian-client-debian:/var/lib/puppet/lib/facter# puppet agent --test
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /var/lib/puppet/lib/facter/vmwaretools_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/esx_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
Info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
Info: Caching catalog for debian-client-debian.lab.lan
Error: Failed to apply catalog: Could not find dependency File[/tmp/vmwaretools] for File[/tmp/vmwaretools/VMwareTools-9.0.5-1065307.tar.gz] at /etc/puppet/environments/production/modules/vmwaretools/manifests/install/archive.pp:27

using openvm-tools
root@debian-client-debian:/var/lib/puppet/lib/facter# apt-get install open-vm-tools
root@debian-client-debian:/var/lib/puppet/lib/facter# puppet agent --test
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /var/lib/puppet/lib/facter/vmwaretools_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/esx_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
Info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
Info: Caching catalog for debian-client-debian.lab.lan
Error: Failed to apply catalog: Could not find dependency File[/tmp/vmwaretools] for File[/tmp/vmwaretools/VMwareTools-9.0.5-1065307.tar.gz] at /etc/puppet/environments/production/modules/vmwaretools/manifests/install/archive.pp:27

**Comment by jgrumboe** [comment]
Uups, sorry for my comment above...i somehow mixed it up with my issue #68.
:x

**Comment by rantamplan** [comment]
the message is present with   $keep_working_dir     = true or false and i have downgraded to 1.3.1 and the message was present

**Comment by craigwatson** [comment]
Thanks - the  `/tmp/vmwaretools` directory are only deployed when the `$::vmwaretools::params::deploy_files` parameter is set to true.

Can you post the output of `facter -p`?

**Comment by rantamplan** [comment]
bios_release_date => 06/22/2012
bios_vendor => Phoenix Technologies LTD
bios_version => 6.00
blockdevice_fd0_size => 0
blockdevice_sda_model => Virtual disk
blockdevice_sda_size => 17179869184
blockdevice_sda_vendor => VMware
blockdevice_sr0_model => VMware IDE CDR10
blockdevice_sr0_size => 1073741312
blockdevice_sr0_vendor => NECVMWar
blockdevices => fd0,sda,sr0
boardmanufacturer => Intel Corporation
boardproductname => 440BX Desktop Reference Platform
boardserialnumber => None
domain => lab.lan
esx_version => 5.1
facterversion => 2.4.3
filesystems => btrfs,ext2,ext3,ext4,hfs,hfsplus,jfs,minix,msdos,ntfs,qnx4,reiserfs,ufs,vfat,xfs
fqdn => debian-client-debian.lab.lan
gid => root
hardwareisa => unknown
hardwaremodel => x86_64
hostname => debian-client-debian
id => root
interfaces => eth0,lo
ipaddress => 192.168.1.63
ipaddress_eth0 => 192.168.1.63
ipaddress_lo => 127.0.0.1
is_pe => false
is_virtual => true
kernel => Linux
kernelmajversion => 3.2
kernelrelease => 3.2.0-4-amd64
kernelversion => 3.2.0
lsbdistcodename => wheezy
lsbdistdescription => Debian GNU/Linux 7.8 (wheezy)
lsbdistid => Debian
lsbdistrelease => 7.8
lsbmajdistrelease => 7
lsbminordistrelease => 8
macaddress => 00:0c:29:b2:de:a9
macaddress_eth0 => 00:0c:29:b2:de:a9
manufacturer => VMware, Inc.
memoryfree => 837.39 MB
memoryfree_mb => 837.39
memorysize => 1002.83 MB
memorysize_mb => 1002.83
mtu_eth0 => 1500
mtu_lo => 16436
netmask => 255.255.255.0
netmask_eth0 => 255.255.255.0
netmask_lo => 255.0.0.0
network_eth0 => 192.168.1.0
network_lo => 127.0.0.0
operatingsystem => Debian
operatingsystemmajrelease => 7
operatingsystemrelease => 7.8
os => {"name"=>"Debian", "family"=>"Debian", "release"=>{"major"=>"7", "minor"=>"8", "full"=>"7.8"}, "lsb"=>{"distcodename"=>"wheezy", "distid"=>"Debian", "distdescription"=>"Debian GNU/Linux 7.8 (wheezy)", "distrelease"=>"7.8", "majdistrelease"=>"7", "minordistrelease"=>"8"}}
osfamily => Debian
partitions => {"sda1"=>{"uuid"=>"af73e1df-f294-49a6-90c6-e1d2d61ef30c", "size"=>"32086016", "filesystem"=>"ext4"}, "sda2"=>{"size"=>"2"}, "sda5"=>{"uuid"=>"f9f80cbf-3264-4709-8211-064e43748a36", "size"=>"1462272", "filesystem"=>"swap"}}
path => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
physicalprocessorcount => 1
processor0 => Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
processor1 => Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
processorcount => 2
processors => {"models"=>["Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz", "Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz"], "count"=>2, "physicalcount"=>1}
productname => VMware Virtual Platform
ps => ps -ef
puppet_vardir => /var/lib/puppet
puppetversion => 3.4.3
root_home => /root
rubyplatform => x86_64-linux
rubysitedir => /usr/local/lib/site_ruby/1.9.1
rubyversion => 1.9.3
selinux => false
serialnumber => VMware-56 4d 17 bd f1 81 63 23-83 35 84 46 6e b2 de a9
sshdsakey => AAAAB3NzaC1kc3MAAACBAIcw2dQNJoe0g+KgPaZXAXKGJE2ai4u27jQMTcB+YxgHlBXhNOhJ428tDP9cszbHPjJDbzeURlj9ImiozVo8RgEA4/toME7Y5tBXbCG2UtpZOw5GBJidbSrs9K6IQQQhomo7gN0UwfxHj9cxMf9Vm79MOiHhWvKJi9DhIOmUxr7/AAAAFQCbDSlfL5YYi9St3++2rZPa9gEZgQAAAIA5oJBtcqZFHxSZlyiqUbeEZIhAVd8yiW6n5PoZXGaRPV2lhwFUGLlT1qgzvngYac+rkOSLfpX+2zIZ4RiZeHfv+MS9K2Z8wXlQXtQ5FoTNXxdAFAsORQocfiCAFyfQ/qq3OxcR3RsE2S4nYY5NwuVNoGYno6i6kbvPuy9pPoua+AAAAIAYhvd9lHoPizuok3hkFRE3qYQ7zO+VoiYL3gXUehlvRNI5Suq6IC9XZ+YMy3DuJLSGx2RzMskf8XlQkIQF5NvX8fm8upgQqMDOGHXNR6JQ5pQQKiSHJZXWJRJqAuwqyPQPjPHe6LMywP1g+W1n39wGF7yP5BoPPCgfiweNtfBiPA==
sshecdsakey => AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJDxBfyfpK+91gfJlpPag3MiVZOmoDKTY26WO/APlbS7kvHIOnOCYxalsAbAMH8ICk7Zyd5qTotTm6S811mgJbY=
sshfp_dsa => SSHFP 2 1 07e4f5b685312e1cd0cd4fcaf6ccb29c87343d3d
SSHFP 2 2 9c7aeca1d7fad43f3e8f13ff2d861ca77d3b4dfc7895f002f527117779ec33c2
sshfp_ecdsa => SSHFP 3 1 3043b0e1d18731b46a51a046f58cd404d8d2a4ea
SSHFP 3 2 f1207e43d3b6a555c633e83db726eea586cd7688d2f0441f66b060ffd0f62f45
sshfp_rsa => SSHFP 1 1 f25d2e00d5ba66f0fef54ce0af21cd381540acd1
SSHFP 1 2 38bb16476c8734ddacaa9e081e68dc346c2f68bbaac9b6e649f7b19a840930cf
sshrsakey => AAAAB3NzaC1yc2EAAAADAQABAAABAQDEKHDaJbU4OPBVB4Wvymv3Gp2rrH9gyLppEisDqWYcEw3BJq3DskxOACiLJwuOxrzX6vT2ogtFBSGV90HWUseLAWXN16dCbIShWhGNSZ8jz1Pr9hJUoEYsxRIVaz/kqfxQKZhZb8qy0jsCVu4mPBWysDgjw8p/ei0n29cT4ceNxe+FlEJy/1c9G3DNnhO0jjUrysfgMMUefJ/e8dhgkmVvcjPEMsXomRksGGKEkYW83SkqDFcCT598WDoJJc7VCq+agT10d+qgNKLGq/oOy85JAJ3C6f+SA3b29JRmzkLAJ1gy9RkfBAJegnb9obLI/B8LmqOoOUKIHnZTVhGE8Yw3
swapfree => 714.00 MB
swapfree_mb => 714.00
swapsize => 714.00 MB
swapsize_mb => 714.00
system_uptime => {"seconds"=>125574, "hours"=>34, "days"=>1, "uptime"=>"1 day"}
timezone => CEST
type => Other
uniqueid => 007f0101
uptime => 1 day
uptime_days => 1
uptime_hours => 34
uptime_seconds => 125574
uuid => 564D17BD-F181-6323-8335-84466EB2DEA9
virtual => vmware
vmwaretools_version => 9.0.5-1065307

**Comment by craigwatson** [comment]
Thanks - can you try using the module version in my 2.0.0 dev branch: https://github.com/craigwatson/puppet-vmwaretools/tree/2.0.0-dev

**Comment by rantamplan** [comment]
for information uninstalling the vmware tools and using this branch i have this message:
root@debian-client-debian:~# puppet agent --test
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /var/lib/puppet/lib/facter/vmwaretools_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/esx_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
Info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Class[Vmwaretools::Install::Archive] is already declared; cannot redeclare at /etc/puppet/environments/production/modules/vmwaretools/manifests/install.pp:33 on node debian-client-debian.lab.lan
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

using open-vm-tools or already installed vmwaretools from vmware :
Error: Failed to apply catalog: Could not find dependency File[/tmp/vmwaretools] for File[/tmp/vmwaretools/VMwareTools-9.0.0-1065307.tar.gz] at /etc/puppet/environments/production/modules/vmwaretools/manifests/install/archive.pp:27

the directory /tmp/vmwaretools isn't created

**Comment by rantamplan** [comment]
update to this branch, modification in foreman (the reason of some error)
uninstalling the vmwaretools and now i have this message each time i run the command: 

root@debian-client-debian:~# puppet agent --test
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /var/lib/puppet/lib/facter/vmwaretools_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/esx_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
Info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
Info: Caching catalog for debian-client-debian.lab.lan
Info: Applying configuration version '1431202411'
Notice: Finished catalog run in 0.62 seconds

So it's seems to be resolved :P

**Comment by craigwatson** [comment]
Perfect, thanks - I've merged this to the master branch, but will wait a day or so to release to the Puppet forge.

Can you test on a brand new deployment?
