### ISSUE TITLE
Not installing on rhel7/centos7

### ISSUE THREAD

**Issue by blackside** [craigwatson/puppet-vmwaretools#65]
Hello, 
Trying to get my vmwaretools installed on my a clean rhel 7 machine

puppet agent -t gives:

....
Info: Caching catalog for rhel7-test.memnon.se
Info: Applying configuration version '1430383137'
Notice: /Stage[main]/Vmwaretools::Config/File[/tmp/vmwaretools]/ensure: created
Notice: /Stage[main]/Vmwaretools::Install::Archive/File[/tmp/vmwaretools/VMwareTools-9.4.11-2400950.tar.gz]/ensure: defined content as '{md5}98bbfe57aa2dd473cbeacb799a000884'
Info: /Stage[main]/Vmwaretools::Install::Archive/File[/tmp/vmwaretools/VMwareTools-9.4.11-2400950.tar.gz]: Scheduling refresh of Exec[uncompress_vmwaretools]
Notice: /Stage[main]/Vmwaretools::Install::Exec/Exec[uncompress_vmwaretools]: Triggered 'refresh' from 1 events
Info: /Stage[main]/Vmwaretools::Install::Exec/Exec[uncompress_vmwaretools]: Scheduling refresh of Exec[install_vmwaretools]
Notice: /Stage[main]/Vmwaretools::Install::Exec/Exec[install_vmwaretools]: Triggered 'refresh' from 1 events
Info: /Stage[main]/Vmwaretools::Install::Exec/Exec[install_vmwaretools]: Scheduling refresh of Exec[clean_vmwaretools]
Notice: /Stage[main]/Vmwaretools::Install::Exec/Exec[clean_vmwaretools]: Triggered 'refresh' from 1 events
Info: /Stage[main]/Vmwaretools::Install::Exec/Exec[clean_vmwaretools]: Scheduling refresh of Exec[remove_vmwaretools_working_dir]
Notice: /Stage[main]/Vmwaretools::Install::Exec/Exec[remove_vmwaretools_working_dir]: Triggered 'refresh' from 1 events
Notice: Finished catalog run in 8.66 seconds

Does this every agent run and never installs. It works on my older rhel6/5 and centos6/5
Only settings I have touched are: $version = '9.4.11-2400950', and added the tar.gz file under files/ folder.
What might be the issue? Feels like Im missing something rhel7 related?

**Comment by craigwatson** [comment]
Hi,

There's a known issue with VMware Tools and RHEL 7 - see #55 for more detail.

To work around, you may need to set the `force_install` parameter to `true` (see the documentation in `init.pp` for more detail on what the parameter does).

I'll add a few notes to the Readme in future, and I'm considering adding a `auto-force` parameter that automatically uses the `force_install` parameter on known-bad OS versions, but this is a non-trivial change and may take a while to fully test :)

Can you confirm that the `force_install` parameter fixes your issue?

Thanks,
Craig

**Comment by blackside** [comment]
Thanks!
Got it working now. I was a bit wary about setting a value like force_install to true ;)
