### ISSUE TITLE
Tools installation failes because open-vm-tools should be used

### ISSUE THREAD

**Issue by Tuxdiver** [craigwatson/puppet-vmwaretools#70]
In my last installation, vmwaretools are not installed because the installer returns:

```
root@v-phabricator (Phabricator-Server):/tmp/vmware-tools-distrib# ./vmware-install.pl -d
open-vm-tools are available from the OS vendor and VMware recommends using
open-vm-tools. See http://kb.vmware.com/kb/2073803 for more information.
Do you still want to proceed with this legacy installer? [no]
```

so installation stops here an starts at next puppet run again.

VMware-Tools:  VMwareTools-9.4.11-2400950.tar.gz
Distro: Ubuntu Trusty

**Comment by craigwatson** [comment]
Hi,

You will need to pass the `force_install` parameter to `true` when using the module - I do plan to make this automatic based on the osfamily and version of VMware, but as always time is my enemy!

Can you let me know if this fixes your problem?

Thanks,
Craig

**Comment by Tuxdiver** [comment]
Hi,
yes, ''force_install'' did help and die uninstall the open-vm-tools and install the original one. Thanks for the quick fix!

Question: if VMware recommends the open-vm-tools, shouldn't your module detect the distributions for that and use the open-vm-tools instead of the other one? Maybe support for open-vm is better in some distributions than the tools from VMware?

**Comment by craigwatson** [comment]
Thanks for confirming - ultimately I think the module is doing it's job, I originally wrote it to install the VMware Tools from tarball as the vSphere console still classes the open-vm-tools as "third party".

After reading the linked [VMware KB article](http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2073803), I'm unsure if any of the benefits are still "benefits" if you're using Puppet to install the "official" Tools (either from tar or OSP), it seems that VMware are recommending installing `open-vm-tools`for convenience.
