### ISSUE TITLE
Timesync dependency issue?

### ISSUE THREAD

**Issue by esalberg** [craigwatson/puppet-vmwaretools#71]
On provisining on a new node, I get the following error for the first Puppet run:

Exec[vmwaretools_timesync_disable] (/etc/puppetlabs/puppet/environments/future_371/modules/vmwaretools/manifests/timesync.pp:39)
Property	Message
Could not find command '/usr/bin/vmware-toolbox-cmd'

This clears on the second Puppet run, but is there a dependency there that should be handled in the module? e.g. for exec { "vmwaretools_timesync_${cmd_action}":

require => Class['vmwaretools::install']

If this is okay, I'll submit a pull request.

**Comment by craigwatson** [comment]
Thanks for the bug report, I've fixed this in commit 01d1104 - can you retest with these changes?

**Comment by esalberg** [comment]
It looks good - thanks!
