### ISSUE TITLE
CentOS 7 issue finished successfully but vmwaretools not installed

### ISSUE THREAD

**Issue by mashayev** [craigwatson/puppet-vmwaretools#75]
Hi Craig,

I found some issue with the module, it happens only on CentOS 7.

I rerun the module manually step by step and found the issue:

[root@server ]# ./vmware-install.pl -d
open-vm-tools are available from the OS vendor and VMware recommends using
open-vm-tools. See http://kb.vmware.com/kb/2073803 for more information.
Do you still want to proceed with this legacy installer? [no]

when you running with flag "-d" and the default is [no] instead of [yes] it doesn't continue the installation.

Any idea how can we workaround this issue in the module?

**Comment by mashayev** [comment]
Update,
I've changed the vmware-install.pl  script to ignore the [no] and packed it back to "VMwareTools-9.4.12-2627939.tar.gz"
Now it's working for me, if possible to change the Puppet module to somehow support\ignore the first worming it will be great.

**Comment by craigwatson** [comment]
Hi,

This issue already has a fix - to force installation, you can set the `force_install` parameter to `true`:

    class { 'vmwaretools':
        force_install => true,
    }

Thanks,
Craig

**Comment by mashayev** [comment]
Sorry Bro,
I missed it, Thanks :)
