### ISSUE TITLE
kernel-devel different than kernel-devel-VERSION for Centos needs adding to module.. Hiera perhaps?

### ISSUE THREAD

**Issue by brahama** [craigwatson/puppet-vmwaretools#76]
Hi Craig!

I run into a problem when the module tries to install kernel-devel for a kernel-lt version.
I want to avoid touchihng your module so i was wondering if the params could be filled with hiera.

I tried adding vmwaretools::redhat_devel_package to hiera for that node only but no luck. Keep seeing
Dependency Package[kernel-devel-3.10.95-1.el6.elrepo.x86_64] Where there should be, kernel-lt-devel-3.10.95-1.el6.elrepo.x86_64

Thanks for the help!

**Comment by craigwatson** [comment]
Hey,

I can add the `lt` kernel to the `params.pp` if statement - can you post the output of `facter -p kernelrelease`?

Thanks,
Craig

**Comment by brahama** [comment]
Sure!
facter -p kernelrelease
3.10.95-1.el6.elrepo.x86_64

Let me put more context. This kernel is from a special repo (elrepo). it has this kernel packages

kernel-lt.x86_64 : The Linux kernel. (The core of any Linux-based operating system.)
kernel-lt-devel.x86_64 : Development package for building kernel modules to match the kernel.
and
kernel-ml.x86_64 : The Linux kernel. (The core of any Linux-based operating system.)
kernel-ml-devel.x86_64 : Development package for building kernel modules to match the kernel.

for the ml, it is
Version     : 4.4.1
Release     : 1.el6.elrepo

Just so you are aware of. Not sure hohw to make both.. I only need the kernel-lt, which i already did, but perhhaps its useful for others.

Just curious, how difficult it is to make that available through hiera?  Just starting. 
Thanks Craig!

**Comment by craigwatson** [comment]
Hi,

Apologies for the delay in looking into this properly!

I've had a look through the code and made a lot of improvements to the way that the module handles installing packages, so can you try with the latest version uploaded to the Puppet Forge - 2.3.0?

If you're running a RedHat-family OS, you shouldn't need kernel development packages installed - the module doesn't manage these unless you explicitly ask it to by setting the `install_devel` parameter to `true` - did you set this in your code?

Thanks,
Craig

**Comment by craigwatson** [comment]
Hi,

Can you please confirm if this is still an issue for you, and if the issue still exists when running version 2.3.0 of the module?

Thanks,
Craig

**Comment by craigwatson** [comment]
Hi,

As nobody has confirmed that this problem still exists, I'm closing the issue. Please feel free to re-open if the problem still exists.

Thanks,
Craig
