### ISSUE TITLE
Module appears to be missing o+r permissions recently

### ISSUE THREAD

**Issue by dhoile** [craigwatson/puppet-vmwaretools#81]
We've been using this module for over a year now, and suddenly when we spin up dynamic environments via r10k we're seeing permissions errors from puppet on this module specifically.

In an environment that has had the module for quite a while the permissions look like this:

> ll cloud/modules/vmwaretools
total 60
drwxr-xr-x.  5 root root  4096 Jan 19 11:48 ./
drwxr-xr-x. 41 root root  4096 Jun  9 13:47 ../
-r--r--r--.  1 root root 12980 Sep 10  2015 CHANGELOG.md
-r--r--r--.  1 root root   989 Sep 10  2015 checksums.json
drwxr-xr-x.  3 root root    19 Jan 19 11:48 lib/
-r--r--r--.  1 root root 11358 Sep 10  2015 LICENSE
drwxr-xr-x.  3 root root  4096 Jan 19 11:48 manifests/
-r--r--r--.  1 root root  1194 Sep 10  2015 metadata.json
-r--r--r--.  1 root root  1616 Sep 10  2015 Rakefile
-r--r--r--.  1 root root  6602 Sep 10  2015 README.md
drwxr-xr-x.  2 root root    28 Jan 19 11:48 templates/

In a newly created environment that has downloaded the module recently from the forge you can see that several files are missing o+r, and our puppet runs are complaining about metadata.json specifically:

ll ftr_oua_rhel6/modules/vmwaretools
total 72
drwxr-xr-x.  5 root root  4096 Jun 17 09:05 ./
drwxr-xr-x. 41 root root  4096 Jun 17 09:06 ../
-r--r-----.  1 root root 13892 Jun 11 10:58 CHANGELOG.md
-r--r--r--.  1 root root  1092 Jun 11 11:11 checksums.json
-r--r-----.  1 root root   439 Sep 12  2015 gemfile
-r--r-----.  1 root root  5529 Sep 12  2015 gemfile.lock
drwxr-xr-x.  3 root root    19 Jun 17 09:05 lib/
-r--r-----.  1 root root 11358 Sep 12  2015 LICENSE
drwxr-xr-x.  3 root root  4096 Jun 17 09:05 manifests/
-r--r-----.  1 root root  1219 Jun 11 11:11 metadata.json
-r--r-----.  1 root root  1616 Sep 12  2015 Rakefile
-r--r-----.  1 root root  6602 Sep 12  2015 README.md
drwxr-xr-x.  2 root root    28 Jun 17 09:05 templates/

This is causing failures in our puppet runs specifically for the vmwaretools module:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Permission denied - /etc/puppetlabs/puppet/environments/ftr_oua_rhel6/modules/vmwaretools/metadata.json at /etc/puppetlabs/puppet/environments/ftr_oua_rhel6/manifests/site.pp:35 on node xwtcvdoboua15.corp.dom
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Our workaround has been to use find to set the permissions in our environments on our puppet master which is tedious to say the least.

**Comment by craigwatson** [comment]
Apologies for this, looks to have been caused by my own restrictive local permissions - this has now been corrected in the newest release to the forge.

Can you please test and let me know?

**Comment by dhoile** [comment]
Looks great!  Thanks for the quick turnaround!

> ll environments/test_vmwaretools/modules/vmwaretools
total 72
drwxr-xr-x.  5 root root  4096 Jun 17 09:50 ./
drwxr-xr-x. 41 root root  4096 Jun 17 09:51 ../
-r--r--r--.  1 root root 14194 Jun 17 09:40 CHANGELOG.md
-r--r--r--.  1 root root  1092 Jun 17 09:40 checksums.json
-r--r--r--.  1 root root   439 Sep 12  2015 gemfile
-r--r--r--.  1 root root  5529 Sep 12  2015 gemfile.lock
drwxr-xr-x.  3 root root    19 Jun 17 09:50 lib/
-r--r--r--.  1 root root 11358 Sep 12  2015 LICENSE
drwxr-xr-x.  3 root root  4096 Jun 17 09:50 manifests/
-r--r--r--.  1 root root  1219 Jun 17 09:40 metadata.json
-r--r--r--.  1 root root  1616 Sep 12  2015 Rakefile
-r--r--r--.  1 root root  6602 Sep 12  2015 README.md
drwxr-xr-x.  2 root root    28 Jun 17 09:50 templates/
