### ISSUE TITLE
manage the net-tools package

### ISSUE THREAD

**Issue by leemachine** [craigwatson/puppet-vmwaretools#87]
Minimal CentOS 7.3 installs do not provide the net-tools package, which provides the ifconfig binary. Please add it to the list of packages managed.

**Comment by craigwatson** [comment]
Hi,

Thanks for raising this!

Managing the `net-tools` package is really out-of-scope for this module as it doesn't really provide any functionality directly to VMware Tools and is more of a utility package - I'd suggest installing this package outside of the module.

Thanks,
Ceaig

**Comment by leemachine** [comment]
Copy. Thanks.
